# Generated by Django 5.0.1 on 2024-02-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.IntegerField()),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=100)),
                ('date_recrut', models.DateTimeField()),
                ('date_detach', models.DateTimeField()),
                ('affect_origine', models.DateTimeField()),
                ('sit_fam', models.CharField(choices=[('M', 'Marié'), ('C', 'Célibataire')], max_length=1)),
            ],
        ),
    ]
