# Generated by Django 5.0.1 on 2024-02-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_affect_origine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='nbr_enfant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
